'use client';
import './globals.css'
import NavBar from '../components/NavBar'
import { MantineProvider } from '@mantine/core'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'bM',
  description: 'Generated by bM team',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar style='string'/>
        {children}
      </body>
    </html>
  )
}
